apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-rclone-admin-transfers
  namespace: stanford-admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
 name: sa-rclone-user-transfers
 namespace: stanford-user