triggers:
- name: drive-transfer-service-api-deploy
  project: mattdv-rclone
  configFilePath: .cloudbuild/cloudbuild-api.yaml
  eventType: push
  includedGitRefs: main
  serviceAccount: "projects/mattdv-rclone/serviceAccounts/cb-drive-transfer-service-api@mattdv-rclone.iam.gserviceaccount.com"
  includedFiles: "^(api/.*)$"
  disabled: false
  substitutions:
    _CB_LOGS_BUCKET: "bkt-mdv-dts-cb-logs"
    _AR_PROJECT_ID: "mattdv-rclone"
    _AR_REGISTRY_NAME: "drive-transfer-service"
    _IMAGE: "api"
    _REGION: "us-central1"
    _REPO_DIR: "api"
- name: drive-transfer-service-ui-deploy
  project: mattdv-rclone
  configFilePath: .cloudbuild/cloudbuild-ui.yaml
  eventType: push
  includedGitRefs: main
  serviceAccount: "projects/mattdv-rclone/serviceAccounts/cb-drive-transfer-service-ui@mattdv-rclone.iam.gserviceaccount.com"
  includedFiles: "^(ui/.*)$"
  disabled: false
  substitutions:
    _CB_LOGS_BUCKET: "bkt-mdv-dts-cb-logs"
    _REPO_DIR: "ui"
- name: bootstrap-terraform-plan-deploy
  project: mattdv-rclone
  configFilePath: .cloudbuild/cloudbuild-tf-plan.yaml
  eventType: pull_request
  includedGitRefs: main
  serviceAccount: "projects/mattdv-rclone/serviceAccounts/sa-drive-transfer-service-tf@mattdv-rclone.iam.gserviceaccount.com"
  includedFiles: "^(terraform/environments/bootstrap/.*)$"
  disabled: false
  substitutions:
    _CB_LOGS_BUCKET: "bkt-mdv-dts-cb-logs"
    _ENVIRONMENT: "bootstrap"
    _AR_PROJECT_ID: "mattdv-rclone"
    _AR_REGISTRY_NAME: "terraform-cloudbuilder"
    _IMAGE: "terraform"
    _TERRAFORM_VERSION: "1.9.5"
    _REGION: "us-central1"
    _REPO_DIR: "terraform"
- name: bootstrap-terraform-apply-deploy
  project: mattdv-rclone
  configFilePath: .cloudbuild/cloudbuild-tf-apply.yaml
  eventType: push
  includedGitRefs: main
  serviceAccount: "projects/mattdv-rclone/serviceAccounts/sa-drive-transfer-service-tf@mattdv-rclone.iam.gserviceaccount.com"
  includedFiles: "^(terraform/environments/bootstrap/.*)$"
  disabled: false
  substitutions:
    _CB_LOGS_BUCKET: "bkt-mdv-dts-cb-logs"
    _ENVIRONMENT: "bootstrap"
    _CB_ARTIFACTS_BUCKET: "bkt-mdv-dts-cb-artifacts"
    _AR_PROJECT_ID: "mattdv-rclone"
    _AR_REGISTRY_NAME: "terraform-cloudbuilder"
    _IMAGE: "terraform"
    _TERRAFORM_VERSION: "1.9.5"
    _REGION: "us-central1"
    _REPO_DIR: "terraform"
- name: dev-terraform-plan-deploy
  project: mattdv-rclone
  configFilePath: .cloudbuild/cloudbuild-tf-plan.yaml
  eventType: pull_request
  includedGitRefs: main
  serviceAccount: "projects/mattdv-rclone/serviceAccounts/sa-drive-transfer-service-tf@mattdv-rclone.iam.gserviceaccount.com"
  includedFiles: "^(terraform/environments/dev/.*)$"
  disabled: false
  substitutions:
    _CB_LOGS_BUCKET: "bkt-mdv-dts-cb-logs"
    _ENVIRONMENT: "dev"
    _AR_PROJECT_ID: "mattdv-rclone"
    _AR_REGISTRY_NAME: "terraform-cloudbuilder"
    _IMAGE: "terraform"
    _TERRAFORM_VERSION: "1.9.5"
    _REGION: "us-central1"
    _REPO_DIR: "terraform"
- name: dev-terraform-apply-deploy
  project: mattdv-rclone
  configFilePath: .cloudbuild/cloudbuild-tf-apply.yaml
  eventType: push
  includedGitRefs: main
  serviceAccount: "projects/mattdv-rclone/serviceAccounts/sa-drive-transfer-service-tf@mattdv-rclone.iam.gserviceaccount.com"
  includedFiles: "^(terraform/environments/dev/.*)$"
  disabled: false
  substitutions:
    _CB_LOGS_BUCKET: "bkt-mdv-dts-cb-logs"
    _ENVIRONMENT: "dev"
    _CB_ARTIFACTS_BUCKET: "bkt-mdv-dts-cb-artifacts"
    _AR_PROJECT_ID: "mattdv-rclone"
    _AR_REGISTRY_NAME: "terraform-cloudbuilder"
    _IMAGE: "terraform"
    _TERRAFORM_VERSION: "1.9.5"
    _REGION: "us-central1"
    _REPO_DIR: "terraform"
- name: terraform-builder-deploy
  project: mattdv-rclone
  configFilePath: .cloudbuild/cloudbuild-tf-builder.yaml
  eventType: push
  includedGitRefs: main
  serviceAccount: "projects/mattdv-rclone/serviceAccounts/cb-container-builder@mattdv-rclone.iam.gserviceaccount.com"
  includedFiles: "^(terraform/modules/terraform-cloudbuilder/.*)$"
  disabled: false
  substitutions:
    _CB_LOGS_BUCKET: "bkt-mdv-dts-cb-logs"
    _AR_PROJECT_ID: "mattdv-rclone"
    _AR_REGISTRY_NAME: "terraform-cloudbuilder"
    _IMAGE: "terraform"
    _TERRAFORM_VERSION: "1.9.5"
    _REGION: "us-central1"
    _REPO_DIR: "terraform/modules/terraform-cloudbuilder"
- name: gcs-fuse-sidecar-deploy
  project: mattdv-rclone
  configFilePath: .cloudbuild/cloudbuild-gcs-fuse.yaml
  eventType: push
  includedGitRefs: main
  serviceAccount: "projects/mattdv-rclone/serviceAccounts/cb-container-builder@mattdv-rclone.iam.gserviceaccount.com"
  includedFiles: "^(terraform/modules/gcs-fuse/.*)$"
  disabled: false
  substitutions:
    _CB_LOGS_BUCKET: "bkt-mdv-dts-cb-logs"
    _AR_PROJECT_ID: "mattdv-rclone"
    _AR_REGISTRY_NAME: "drive-transfer-service"
    _IMAGE: "gcs-fuse-csi-driver-sidecar-mounter"
    # IMPORTANT: THIS BELOW "_GCS_FUSE_VERSION_SHA" VALUE SHOULD CHANGE ACCORDING TO GKE VERSION 
    # (https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/blob/main/docs/releases.md#gke-compatibility)
    _GCS_FUSE_VERSION_SHA: "a527a083127fb456c96a6e4a478639222065dc0c2d485729e63605035d624f8f"
    _REGION: "us-central1"