triggers:
- name: drive-transfer-service-api-deploy
  project: [PROJECT_ID]
  eventType: push
  includedGitRefs: main
  serviceAccount: cb-drive-transfer-service-api@[PROJECT_ID].iam.gserviceaccount.com
  includedFiles: "^(api/.*)$"
  disabled: false
  substitutions:
    _AR_PROJECT_ID: "[PROJECT_ID]"
    _AR_REGISTRY_NAME: "drive-transfer-service"
    _COMMIT_SHA: "$(body.after)"
    _IMAGE: "api"
    _REGION: "[DEFAULT_REGION]"
    _REPO_DIR: "api"
- name: drive-transfer-service-ui-deploy
  project: [PROJECT_ID]
  eventType: push
  includedGitRefs: main
  serviceAccount: cb-drive-transfer-service-ui@[PROJECT_ID].iam.gserviceaccount.com
  includedFiles: "^(ui/.*)$"
  disabled: false
  substitutions:
    _REPO_DIR: "ui"
- name: bootstrap-terraform-plan-deploy
  project: [PROJECT_ID]
  eventType: pull_request
  includedGitRefs: main
  serviceAccount: sa-drive-transfer-service-tf@[PROJECT_ID].iam.gserviceaccount.com
  includedFiles: "^(terraform/environments/bootstrap/.*)$"
  disabled: false
  substitutions:
    _AR_PROJECT_ID: "[PROJECT_ID]"
    _AR_REGISTRY_NAME: "terraform-cloudbuilder"
    _IMAGE: "terraform"
    _TERRAFORM_VERSION: "1.9.5"
    _REGION: "[DEFAULT_REGION]"
    _REPO_DIR: "terraform"
- name: bootstrap-terraform-apply-deploy
  project: [PROJECT_ID]
  eventType: push
  includedGitRefs: main
  serviceAccount: sa-drive-transfer-service-tf@[PROJECT_ID].iam.gserviceaccount.com
  includedFiles: "^(terraform/environments/bootstrap/.*)$"
  disabled: false
  substitutions:
    _AR_PROJECT_ID: "[PROJECT_ID]"
    _AR_REGISTRY_NAME: "terraform-cloudbuilder"
    _IMAGE: "terraform"
    _TERRAFORM_VERSION: "1.9.5"
    _REGION: "[DEFAULT_REGION]"
    _REPO_DIR: "terraform"
- name: [ENVIRONMENT]-terraform-plan-deploy
  project: [PROJECT_ID]
  eventType: pull_request
  includedGitRefs: main
  serviceAccount: sa-drive-transfer-service-tf@[PROJECT_ID].iam.gserviceaccount.com
  includedFiles: "^(terraform/environments/[ENVIRONMENT]/.*)$"
  disabled: false
  substitutions:
    _AR_PROJECT_ID: "[PROJECT_ID]"
    _AR_REGISTRY_NAME: "terraform-cloudbuilder"
    _IMAGE: "terraform"
    _TERRAFORM_VERSION: "1.9.5"
    _REGION: "[DEFAULT_REGION]"
    _REPO_DIR: "terraform"
- name: [ENVIRONMENT]-terraform-apply-deploy
  project: [PROJECT_ID]
  eventType: push
  includedGitRefs: main
  serviceAccount: sa-drive-transfer-service-tf@[PROJECT_ID].iam.gserviceaccount.com
  includedFiles: "^(terraform/environments/[ENVIRONMENT]/.*)$"
  disabled: false
  substitutions:
    _AR_PROJECT_ID: "[PROJECT_ID]"
    _AR_REGISTRY_NAME: "terraform-cloudbuilder"
    _IMAGE: "terraform"
    _TERRAFORM_VERSION: "1.9.5"
    _REGION: "[DEFAULT_REGION]"
    _REPO_DIR: "terraform"
- name: terraform-builder-deploy
  project: [PROJECT_ID]
  eventType: push
  includedGitRefs: main
  serviceAccount: cb-container-builder@[PROJECT_ID].iam.gserviceaccount.com
  includedFiles: "^(terraform/modules/terraform-cloudbuilder/.*)$"
  disabled: false
  substitutions:
    _AR_PROJECT_ID: "[PROJECT_ID]"
    _AR_REGISTRY_NAME: "terraform-cloudbuilder"
    _IMAGE: "terraform"
    _TERRAFORM_VERSION: "1.9.5"
    _REGION: "[DEFAULT_REGION]"
    _REPO_DIR: "terraform/modules/terraform-cloudbuilder"
- name: gcs-fuse-sidecar-deploy
  project: [PROJECT_ID]
  eventType: push
  includedGitRefs: main
  serviceAccount: cb-container-builder@[PROJECT_ID].iam.gserviceaccount.com
  includedFiles: "^(terraform/modules/gcs-fuse/.*)$"
  disabled: false
  substitutions:
    _AR_PROJECT_ID: "[PROJECT_ID]"
    _AR_REGISTRY_NAME: "drive-transfer-service"
    _IMAGE: "gcs-fuse-csi-driver-sidecar-mounter"
    _GCS_FUSE_VERSION_SHA: "a527a083127fb456c96a6e4a478639222065dc0c2d485729e63605035d624f8f"
    _REGION: "[DEFAULT_REGION]"